.TH openstack-status "1" "April 2012" "openstack-utils" "User Commands"
.SH NAME
openstack-status - Show status overview of installed OpenStack services
.SH SYNOPSIS
.B openstack-status
.SH DESCRIPTION
Query the system for installed OpenStack services and display
both the running state and basic information managed by those services.
