.TH openstack-config "1" "April 2012" "openstack-utils" "User Commands"
.SH NAME
openstack-config - Manipulate the OpenStack ini files
.SH SYNOPSIS
.B openstack-config
\fI--set|--del config_file section \fR[parameter] [value]
.SH DESCRIPTION
Provide functionality to add/edit/delete items and
sections in the OpenStack ini format config files.
.SH OPTIONS
.HP
\fB\-\-set\fR
.IP
Add/Edit the specified parameter
.HP
\fB\-\-del\fR
.IP
Remove the specified parameter or section
.SH SEE ALSO
This command is deprecated.
Please consider using the more featureful crudini(1).
