.TH openstack-demo-install "1" "April 2012" "openstack-utils" "User Commands"
.SH NAME
openstack-demo-install - Setup all services on a single node for testing
.SH SYNOPSIS
.B openstack-demo-install
.SH DESCRIPTION
Install all OpenStack services on a single node with a default configuration,
useful for testing.

