.TH openstack-service "1" "October 2013" "openstack-utils" "User Commands"
.SH NAME
openstack-service - Control enabled openstack services
.SH SYNOPSIS
.B openstack-service
\fI<action> \fR[\fIservice\fR]...
.SH DESCRIPTION
 <action> can be 'list' or an action supported by the service.
 'list' will list the enabled openstack services.
 Any specified [service]s filter the list of enabled openstack services.
.SH SEE ALSO
openstack-status(1)
